name: Hello Template
on:
  workflow_call:
    inputs:
      prenom:
        description: Prénom à saluer.
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Saluer la personne
        env:
          PRENOM: ${{ inputs.prenom }}
        run: echo "Bonjour ${PRENOM} depuis le workflow réutilisable !"
        shell: bash
